// GET
export const START_FETCH = 'START_FETCH'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'

// POST
export const START_CREATE_TEST = 'START_CREATE_TEST'
export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS'
export const CREATE_TEST_ERROR = 'CREATE_TEST_ERROR'

// SELECT AN ITEM
export const SELECT_AN_ITEM = 'SELECT_AN_ITEM'